In [1]:
import pandas as pd

In [2]:
data={'Customer_ID': [101, 102, 103, 101, 104, 102, 101, 105, 102, 103],
      'Purchase_Amount': [200, 150, 180, 220, 300, 200, 100, 400, 250, 300]}
#Calculate total purchase amount per customer
#Identify the top 3 customers with the highest purchase amounts

In [3]:
df = pd.DataFrame(data)

In [4]:
df

Customer_ID  Purchase_Amount
0          101              200
1          102              150
2          103              180
3          101              220
4          104              300
5          102              200
6          101              100
7          105              400
8          102              250
9          103              300

In [5]:
df.head(3)

Customer_ID  Purchase_Amount
0          101              200
1          102              150
2          103              180

In [6]:
df.sum()

Customer_ID        1024
Purchase_Amount    2300
dtype: int64

In [7]:
df.mean()

Customer_ID        102.4
Purchase_Amount    230.0
dtype: float64

In [8]:
df.max()

Customer_ID        105
Purchase_Amount    400
dtype: int64

In [9]:
df.describe()

Customer_ID  Purchase_Amount
count    10.000000         10.00000
mean    102.400000        230.00000
std       1.349897         86.15232
min     101.000000        100.00000
25%     101.250000        185.00000
50%     102.000000        210.00000
75%     103.000000        287.50000
max     105.000000        400.00000

In [10]:
df.describe().sum()

Customer_ID         625.999897
Purchase_Amount    1508.652320
dtype: float64

In [11]:
#gruop by and sum cus_ID ,purchase_amount
total_purchase_amount = df.groupby('Customer_ID')['Purchase_Amount'].sum().reset_index()

In [12]:
total_purchase_amount

Customer_ID  Purchase_Amount
0          101              520
1          102              600
2          103              480
3          104              300
4          105              400

In [13]:
#sort
top_customers = total_purchase_amount.sort_values(by='Purchase_Amount',ascending=False).head(3)   

In [14]:
print(top_customers)

   Customer_ID  Purchase_Amount
1          102              600
0          101              520
2          103              480


In [15]:
#real estate price
df = {'Square_Feet': [1500, 2000, 2500, 3000, 3500],
      'Price': [300000, 400000, 500000, 600000, 700000]}

In [16]:
import pandas as pd
df = pd.DataFrame(df)


In [17]:
df

Square_Feet   Price
0         1500  300000
1         2000  400000
2         2500  500000
3         3000  600000
4         3500  700000

In [18]:
Independent = df[["Square_Feet"]]
Independent

Square_Feet
0         1500
1         2000
2         2500
3         3000
4         3500

In [19]:
dependent = df[["Price"]]
dependent

Price
0  300000
1  400000
2  500000
3  600000
4  700000

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Independent, dependent,test_size=0.30,random_state=0)

In [21]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [22]:
weight=regressor.coef_
weight

array([[200.]])

In [23]:
basis=regressor.intercept_
basis

array([0.])

In [24]:
y_pred=regressor.predict(X_test)

In [25]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [26]:
r_score

1.0

In [27]:
import pickle
filename="finalized_model_Linear.sav"

In [28]:
pickle.dump(regressor,open(filename,'wb'))

In [29]:
import pickle

In [30]:
loaded_model=pickle.load(open("finalized_model_Linear.sav",'rb'))
result=loaded_model.predict([[1800], [2800]])

C:\Users\Admin\anaconda3\envs\adml\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [31]:
result

array([[360000.],
       [560000.]])

In [32]:
#predicted Price:[360000.],[560000.]

In [33]:
import pandas as pd

In [34]:
data = {'Category':['A', 'B', 'C', 'A', 'D', 'B', 'A', 'E', 'B', 'C', 'C', 'A'],
        'Value': [10, 15, 20, 30, 25, 18, 22, 40, 35, 50, 45, 15]}

In [35]:
df = pd.DataFrame(data)

In [36]:
df

Category  Value
0         A     10
1         B     15
2         C     20
3         A     30
4         D     25
5         B     18
6         A     22
7         E     40
8         B     35
9         C     50
10        C     45
11        A     15

In [37]:
#count
category_counts = df['Category'].value_counts()

In [38]:
category_counts

Category
A    4
B    3
C    3
D    1
E    1
Name: count, dtype: int64

In [39]:
#top 3 most frequent category
top_3_categories = category_counts.nlargest(3)

In [40]:
top_3_categories

Category
A    4
B    3
C    3
Name: count, dtype: int64

In [44]:
import pandas as pd
def identify_top_categories():
    data = {'Category':['A', 'B', 'C', 'A', 'D', 'B', 'A', 'E', 'B', 'C', 'C', 'A'],
        'Value': [10, 15, 20, 30, 25, 18, 22, 40, 35, 50, 45, 15]}
    df = pd.DataFrame(data)
    category_counts = df['Category'].value_counts()
    top_3_categories = category_counts.nlargest(3)
    return top_3_categories
    
    
    
    
    


In [45]:
top_categories = identify_top_categories()
print(top_categories)

Category
A    4
B    3
C    3
Name: count, dtype: int64


In [46]:
import pandas as pd

In [48]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25,30,None,35,None]}

In [49]:
df=pd.DataFrame(data)

In [50]:
df

Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie   NaN
3    David  35.0
4      Eve   NaN

In [51]:
mean_age = df['Age'].mean()

In [52]:
mean_age

30.0

In [53]:
df['Age'] = df['Age'].fillna(mean_age)

In [54]:
df

Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  30.0
3    David  35.0
4      Eve  30.0

In [57]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [58]:
data = {'Experience': [1, 2, 3, 4, 5],
        'Salary': [30000, 35000,40000, 45000, 500000]}


In [60]:
df= pd.DataFrame(data)

In [61]:
df

Experience  Salary
0           1   30000
1           2   35000
2           3   40000
3           4   45000
4           5  500000

In [62]:
X = df[['Experience']]
y = df['Salary']

In [63]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [65]:
new_data = {'Experience': [6]}
new_data = pd.DataFrame(new_data)
predicted_salary = model.predict(new_data)
print("predicted salary for an individual with 6 years of experience:", predicted_salary[0])

predicted salary for an individual with 6 years of experience: 414999.99999999994
