In [1]:
import pandas as pd


In [2]:
data={'Feature1': ['10', '20', '30'],
      'Feature2': [5.5,6.7,8.9]}
      

In [3]:
df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)

In [4]:
print(df)

   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [5]:
import pandas as pd
data = {'A': [1, 2, None],
        'B': [4,None, 6]}
df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)
print(df)

     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0


In [6]:
from sklearn.linear_model import LinearRegression
import numpy as np
x = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
y = np.array([2, 4, 6, 8, 10])
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [7]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data = np.array([10, 20, 30, 40, 50]).reshape(-1, 1)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [8]:
from sklearn.linear_model import LogisticRegression
X = [[1, 2], [3, 4], [5, 6]]
y = ['1', '0', '1']
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [9]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])
print(encoded.toarray())
                   
                   

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [10]:
from sklearn.model_selection import train_test_split
X = [[1, 2], [3, 4], [5, 6], [7, 8]] 
y = [0, 1, 0, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [11]:
from sklearn.linear_model import LogisticRegression
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ['1', '0', '1']
model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [13]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train_imputed, y_train)


LinearRegression()

In [14]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
X_train = np.array ( [[1, 2], [3, 4], [5, 6]])

y_train = np.array(["spam", "ham", "spam"])
#map string labels to numerical values
label_mapping = {"spam": 0, "ham": 1}
y_train_mapped = np.array([label_mapping[label] for label in y_train])
model = DecisionTreeClassifier()
model.fit(X_train, y_train_mapped)
                 



DecisionTreeClassifier()

In [17]:
from sklearn.svm import SVC
X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]
model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))

[0]
